import {
  PUBLIC_CESIUM_ION_TOKEN,
  PUBLIC_BERLIN_ION_ASSET_ID,
  PUBLIC_BERLIN_TILES_URL,
} from "$env/static/public";

/**
 * Berlin Flight Experience Constants
 */
export const BERLIN_CESIUM_ION_TOKEN = PUBLIC_CESIUM_ION_TOKEN;
export const BERLIN_ION_ASSET_ID = Number(PUBLIC_BERLIN_ION_ASSET_ID);
export const BERLIN_TILES_URL = PUBLIC_BERLIN_TILES_URL;

export const BERLIN_FLIGHT_BASE_SPEED = 20;

export const BERLIN_ALTITUDE_SPEED = {
  MIN_ALTITUDE: 35,
  MAX_ALTITUDE: 450,
  MIN_MULTIPLIER: 0.45,
  MAX_MULTIPLIER: 3,
} as const;

export const BERLIN_CONE_GRID = {
  SPACING: 240,
  ORIGIN_HEIGHT: 140,
  CONE_RADIUS: 48,
  CONE_HEIGHT: 180,
  COLOR: 0xff4fd8,
  CHUNK_CONES_PER_SIDE: 8,
  LOAD_RADIUS_CHUNKS: 2,
  UNLOAD_RADIUS_CHUNKS: 3,
  MAX_CHUNK_LOADS_PER_TICK: 3,
} as const;

export const BERLIN_COLLISION = {
  MAX_MESHES_PER_TICK: 8,
} as const;

export const BERLIN_TILE_LOOK = {
  NEUTRAL_COLOR: 0xbecad3,
  METALNESS: 0,
  OPACITY: 0.68,
  ROUGHNESS: 0.52,
} as const;
