export const BERLIN_DEBUG_OVERLAY_DEFAULT = false;
export const BERLIN_DEBUG_OVERLAY_UPDATE_SECONDS = 0.25;
export const BERLIN_DEBUG_OVERLAY_WIDTH = 512;
export const BERLIN_DEBUG_OVERLAY_HEIGHT = 256;
